### ISSUE TITLE
Update sample READMEs with correct Python SDK link

### ISSUE THREAD

**Issue by dime10** [microsoft/qio-samples#13]
I think all the individual sample READMEs still use the https://docs.microsoft.com/azure/quantum/how-to-use-the-python-sdk link in their prerequisites, which gives a 404. The correct link should be https://docs.microsoft.com/azure/quantum/optimization-install-sdk.

**Comment by danielstocker** [comment]
Hey @dime10 - I'm having a look through them now. Thanks for catching this.

**Comment by danielstocker** [comment]
I've opened up https://github.com/microsoft/qio-samples/pull/16 - have done a bulk replace

**Comment by frtibble** [comment]
Thank you @dime10 and @danielstocker - this has now been merged
